graph TD
    C_10["Инвестирование и учет времени"]
    C_11["Исчезающие заметки"]
    C_12["Калибр личности"]
    C_13["Карта ролей / карта системы карьеры"]
    C_14["Карьера"]
    C_15["Карьерный рост"]
    C_16["Киберличность"]
    C_17["Конвейер работ"]
    C_18["Конструктивное выравнивание"]
    C_19["Консультанты и карьерные трекеры"]
    C_1["«Ворота» между стадиями"]
    C_20["Критерии приёмки"]
    C_21["Крошки времени"]
    C_22["Личный контракт"]
    C_23["Мастерство (компетенции)"]
    C_24["Мимолетные заметки (синоним «Исчезающие заметки»)"]
    C_25["Мыслительный резонанс"]
    C_26["Мышление письмом"]
    C_27["Недельное стратегирование"]
    C_28["Недельный цикл"]
    C_29["Неудовлетворённость"]
    C_2["Агентность"]
    C_30["Онтологический дребезг"]
    C_31["Осознанное обучение (vs интуитивное)"]
    C_32["Пассажирский режим"]
    C_33["Показатели прогресса"]
    C_34["Правила качества"]
    C_35["Практики саморазвития / Новая (вторая) грамотность"]
    C_36["Приоритетный инвестиционный проект"]
    C_37["Приоритетный проект"]
    C_38["Приоритетный рабочий проект"]
    C_39["Продуктивное состояние"]
    C_3["Бренд личности"]
    C_40["Проблема"]
    C_41["Пропитка"]
    C_42["Профессионал"]
    C_43["Публичность и репутация"]
    C_44["Рабочий продукт (артефакт)"]
    C_45["Репутация"]
    C_46["Роль"]
    C_47["Синергетический эффект (практик)"]
    C_48["Системная карьера"]
    C_49["Системное саморазвитие"]
    C_4["Взаимная рецензия (peer review)"]
    C_50["Слоты"]
    C_51["Спринт (неделя)"]
    C_52["Стадии обучения"]
    C_53["Стратегирование"]
    C_54["Творческий конвейер"]
    C_55["Творческий щелчок"]
    C_56["Техноэволюция"]
    C_57["Траектория ролей"]
    C_58["Уровни мастерства"]
    C_59["Устойчивая карьера (Sustainable Career)"]
    C_5["Должность"]
    C_60["Формирование окружения"]
    C_61["Целенаправленное зондирование"]
    C_62["Чувство"]
    C_63["Шкура на кону (Skin in the game)"]
    C_64["Экзокортекс / Второй мозг (Second Brain)"]
    C_65["Элита"]
    C_66["Эмоции"]
    C_67["Этические фильтры / «красные зоны»"]
    C_68["Эпик"]
    C_6["Жизненное мастерство"]
    C_7["Заготовка"]
    C_8["Инкремент"]
    C_9["Интенсивность эмоций"]
    C_10 -->|relates_to| C_21
    C_10 -->|relates_to| C_27
    C_10 -->|relates_to| C_28
    C_10 -->|relates_to| C_35
    C_10 -->|relates_to| C_36
    C_10 -->|relates_to| C_37
    C_10 -->|relates_to| C_50
    C_10 -->|relates_to| C_51
    C_10 -->|relates_to| C_53
    C_11 -->|relates_to| C_24
    C_11 -->|relates_to| C_26
    C_11 -->|relates_to| C_54
    C_12 -->|relates_to| C_2
    C_12 -->|relates_to| C_3
    C_12 -->|relates_to| C_23
    C_12 -->|relates_to| C_43
    C_12 -->|relates_to| C_45
    C_12 -->|relates_to| C_46
    C_13 -->|relates_to| C_46
    C_13 -->|relates_to| C_14
    C_13 -->|relates_to| C_48
    C_13 -->|relates_to| C_27
    C_14 -->|relates_to| C_13
    C_14 -->|relates_to| C_15
    C_14 -->|relates_to| C_48
    C_14 -->|relates_to| C_2
    C_14 -->|relates_to| C_23
    C_14 -->|relates_to| C_43
    C_14 -->|relates_to| C_45
    C_14 -->|relates_to| C_46
    C_15 -->|relates_to| C_14
    C_15 -->|relates_to| C_23
    C_15 -->|relates_to| C_46
    C_15 -->|relates_to| C_33
    C_15 -->|relates_to| C_53
    C_15 -->|relates_to| C_27
    C_16 -->|relates_to| C_3
    C_16 -->|relates_to| C_43
    C_16 -->|relates_to| C_45
    C_16 -->|relates_to| C_44
    C_17 -->|relates_to| C_1
    C_17 -->|relates_to| C_28
    C_17 -->|relates_to| C_37
    C_17 -->|relates_to| C_38
    C_17 -->|relates_to| C_44
    C_17 -->|relates_to| C_50
    C_17 -->|relates_to| C_51
    C_17 -->|relates_to| C_54
    C_18 -->|relates_to| C_20
    C_18 -->|relates_to| C_23
    C_18 -->|relates_to| C_31
    C_18 -->|relates_to| C_33
    C_18 -->|relates_to| C_35
    C_18 -->|relates_to| C_46
    C_18 -->|relates_to| C_53
    C_19 -->|relates_to| C_2
    C_19 -->|relates_to| C_14
    C_19 -->|relates_to| C_15
    C_19 -->|relates_to| C_27
    C_19 -->|relates_to| C_48
    C_19 -->|relates_to| C_53
    C_1 -->|relates_to| C_20
    C_1 -->|relates_to| C_23
    C_1 -->|relates_to| C_33
    C_1 -->|relates_to| C_52
    C_20 -->|relates_to| C_27
    C_20 -->|relates_to| C_28
    C_20 -->|relates_to| C_34
    C_20 -->|relates_to| C_44
    C_20 -->|relates_to| C_51
    C_21 -->|relates_to| C_10
    C_21 -->|relates_to| C_11
    C_21 -->|relates_to| C_24
    C_21 -->|relates_to| C_28
    C_21 -->|relates_to| C_50
    C_21 -->|relates_to| C_51
    C_22 -->|relates_to| C_2
    C_22 -->|relates_to| C_20
    C_22 -->|relates_to| C_27
    C_22 -->|relates_to| C_33
    C_22 -->|relates_to| C_51
    C_23 -->|relates_to| C_31
    C_23 -->|relates_to| C_35
    C_23 -->|relates_to| C_42
    C_23 -->|relates_to| C_45
    C_23 -->|relates_to| C_52
    C_24 -->|relates_to| C_11
    C_24 -->|relates_to| C_26
    C_24 -->|relates_to| C_44
    C_25 -->|relates_to| C_26
    C_25 -->|relates_to| C_39
    C_25 -->|relates_to| C_27
    C_25 -->|relates_to| C_53
    C_25 -->|relates_to| C_55
    C_26 -->|relates_to| C_11
    C_26 -->|relates_to| C_24
    C_26 -->|relates_to| C_25
    C_26 -->|relates_to| C_27
    C_26 -->|relates_to| C_53
    C_27 -->|relates_to| C_28
    C_27 -->|relates_to| C_51
    C_27 -->|relates_to| C_53
    C_27 -->|relates_to| C_50
    C_27 -->|relates_to| C_33
    C_27 -->|relates_to| C_36
    C_27 -->|relates_to| C_37
    C_27 -->|relates_to| C_38
    C_28 -->|relates_to| C_27
    C_28 -->|relates_to| C_51
    C_28 -->|relates_to| C_36
    C_28 -->|relates_to| C_37
    C_28 -->|relates_to| C_38
    C_28 -->|relates_to| C_33
    C_28 -->|relates_to| C_22
    C_28 -->|relates_to| C_10
    C_29 -->|relates_to| C_2
    C_29 -->|relates_to| C_27
    C_29 -->|relates_to| C_53
    C_29 -->|relates_to| C_46
    C_29 -->|relates_to| C_14
    C_2 -->|relates_to| C_32
    C_2 -->|relates_to| C_27
    C_2 -->|relates_to| C_48
    C_2 -->|relates_to| C_49
    C_30 -->|relates_to| C_13
    C_30 -->|relates_to| C_23
    C_30 -->|relates_to| C_27
    C_30 -->|relates_to| C_44
    C_30 -->|relates_to| C_46
    C_30 -->|relates_to| C_53
    C_31 -->|relates_to| C_23
    C_31 -->|relates_to| C_33
    C_31 -->|relates_to| C_35
    C_31 -->|relates_to| C_49
    C_31 -->|relates_to| C_52
    C_32 -->|relates_to| C_2
    C_32 -->|relates_to| C_29
    C_32 -->|relates_to| C_39
    C_32 -->|relates_to| C_53
    C_33 -->|relates_to| C_27
    C_33 -->|relates_to| C_28
    C_33 -->|relates_to| C_36
    C_33 -->|relates_to| C_37
    C_33 -->|relates_to| C_38
    C_33 -->|relates_to| C_51
    C_33 -->|relates_to| C_53
    C_34 -->|relates_to| C_4
    C_34 -->|relates_to| C_20
    C_34 -->|relates_to| C_23
    C_34 -->|relates_to| C_42
    C_34 -->|relates_to| C_44
    C_35 -->|relates_to| C_11
    C_35 -->|relates_to| C_27
    C_35 -->|relates_to| C_31
    C_35 -->|relates_to| C_26
    C_35 -->|relates_to| C_4
    C_35 -->|relates_to| C_49
    C_35 -->|relates_to| C_23
    C_35 -->|relates_to| C_2
    C_36 -->|relates_to| C_10
    C_36 -->|relates_to| C_23
    C_36 -->|relates_to| C_37
    C_36 -->|relates_to| C_38
    C_36 -->|relates_to| C_27
    C_36 -->|relates_to| C_28
    C_37 -->|relates_to| C_36
    C_37 -->|relates_to| C_38
    C_37 -->|relates_to| C_27
    C_37 -->|relates_to| C_28
    C_37 -->|relates_to| C_51
    C_37 -->|relates_to| C_53
    C_37 -->|relates_to| C_33
    C_37 -->|relates_to| C_20
    C_38 -->|relates_to| C_36
    C_38 -->|relates_to| C_37
    C_38 -->|relates_to| C_1
    C_38 -->|relates_to| C_27
    C_38 -->|relates_to| C_28
    C_38 -->|relates_to| C_50
    C_38 -->|relates_to| C_51
    C_39 -->|relates_to| C_10
    C_39 -->|relates_to| C_21
    C_39 -->|relates_to| C_27
    C_39 -->|relates_to| C_28
    C_39 -->|relates_to| C_32
    C_39 -->|relates_to| C_36
    C_39 -->|relates_to| C_50
    C_39 -->|relates_to| C_51
    C_3 -->|relates_to| C_43
    C_3 -->|relates_to| C_45
    C_3 -->|relates_to| C_16
    C_40 -->|relates_to| C_2
    C_40 -->|relates_to| C_14
    C_40 -->|relates_to| C_23
    C_40 -->|relates_to| C_29
    C_40 -->|relates_to| C_33
    C_40 -->|relates_to| C_45
    C_40 -->|relates_to| C_53
    C_41 -->|relates_to| C_23
    C_41 -->|relates_to| C_27
    C_41 -->|relates_to| C_31
    C_41 -->|relates_to| C_35
    C_41 -->|relates_to| C_49
    C_41 -->|relates_to| C_52
    C_42 -->|relates_to| C_2
    C_42 -->|relates_to| C_14
    C_42 -->|relates_to| C_22
    C_42 -->|relates_to| C_23
    C_42 -->|relates_to| C_43
    C_42 -->|relates_to| C_46
    C_42 -->|relates_to| C_48
    C_43 -->|relates_to| C_3
    C_43 -->|relates_to| C_16
    C_43 -->|relates_to| C_45
    C_43 -->|relates_to| C_23
    C_43 -->|relates_to| C_42
    C_44 -->|relates_to| C_20
    C_44 -->|relates_to| C_33
    C_44 -->|relates_to| C_4
    C_44 -->|relates_to| C_43
    C_44 -->|relates_to| C_45
    C_45 -->|relates_to| C_3
    C_45 -->|relates_to| C_43
    C_45 -->|relates_to| C_23
    C_45 -->|relates_to| C_46
    C_46 -->|relates_to| C_13
    C_46 -->|relates_to| C_14
    C_46 -->|relates_to| C_23
    C_46 -->|relates_to| C_42
    C_46 -->|relates_to| C_48
    C_47 -->|relates_to| C_10
    C_47 -->|relates_to| C_11
    C_47 -->|relates_to| C_26
    C_47 -->|relates_to| C_27
    C_47 -->|relates_to| C_31
    C_47 -->|relates_to| C_35
    C_47 -->|relates_to| C_43
    C_47 -->|relates_to| C_54
    C_48 -->|relates_to| C_2
    C_48 -->|relates_to| C_13
    C_48 -->|relates_to| C_14
    C_48 -->|relates_to| C_15
    C_48 -->|relates_to| C_23
    C_48 -->|relates_to| C_27
    C_48 -->|relates_to| C_28
    C_48 -->|relates_to| C_35
    C_48 -->|relates_to| C_43
    C_48 -->|relates_to| C_46
    C_48 -->|relates_to| C_49
    C_48 -->|relates_to| C_51
    C_48 -->|relates_to| C_53
    C_49 -->|relates_to| C_35
    C_49 -->|relates_to| C_31
    C_49 -->|relates_to| C_48
    C_49 -->|relates_to| C_27
    C_49 -->|relates_to| C_28
    C_49 -->|relates_to| C_33
    C_49 -->|relates_to| C_23
    C_4 -->|relates_to| C_23
    C_4 -->|relates_to| C_44
    C_4 -->|relates_to| C_34
    C_50 -->|relates_to| C_10
    C_50 -->|relates_to| C_27
    C_50 -->|relates_to| C_28
    C_50 -->|relates_to| C_51
    C_51 -->|relates_to| C_27
    C_51 -->|relates_to| C_28
    C_51 -->|relates_to| C_33
    C_51 -->|relates_to| C_36
    C_51 -->|relates_to| C_37
    C_51 -->|relates_to| C_38
    C_52 -->|relates_to| C_1
    C_52 -->|relates_to| C_23
    C_52 -->|relates_to| C_31
    C_52 -->|relates_to| C_33
    C_52 -->|relates_to| C_35
    C_53 -->|relates_to| C_27
    C_53 -->|relates_to| C_28
    C_53 -->|relates_to| C_36
    C_53 -->|relates_to| C_37
    C_53 -->|relates_to| C_38
    C_53 -->|relates_to| C_10
    C_53 -->|relates_to| C_2
    C_53 -->|relates_to| C_14
    C_53 -->|relates_to| C_46
    C_53 -->|relates_to| C_23
    C_54 -->|relates_to| C_17
    C_54 -->|relates_to| C_11
    C_54 -->|relates_to| C_24
    C_54 -->|relates_to| C_26
    C_54 -->|relates_to| C_44
    C_54 -->|relates_to| C_43
    C_55 -->|relates_to| C_54
    C_55 -->|relates_to| C_25
    C_55 -->|relates_to| C_39
    C_56 -->|relates_to| C_2
    C_56 -->|relates_to| C_23
    C_56 -->|relates_to| C_31
    C_56 -->|relates_to| C_35
    C_56 -->|relates_to| C_49
    C_56 -->|relates_to| C_53
    C_57 -->|relates_to| C_13
    C_57 -->|relates_to| C_14
    C_57 -->|relates_to| C_15
    C_57 -->|relates_to| C_23
    C_57 -->|relates_to| C_46
    C_57 -->|relates_to| C_48
    C_57 -->|relates_to| C_53
    C_58 -->|relates_to| C_23
    C_58 -->|relates_to| C_31
    C_58 -->|relates_to| C_52
    C_58 -->|relates_to| C_42
    C_58 -->|relates_to| C_15
    C_59 -->|relates_to| C_2
    C_59 -->|relates_to| C_14
    C_59 -->|relates_to| C_15
    C_59 -->|relates_to| C_23
    C_59 -->|relates_to| C_27
    C_59 -->|relates_to| C_35
    C_59 -->|relates_to| C_39
    C_59 -->|relates_to| C_48
    C_59 -->|relates_to| C_49
    C_59 -->|relates_to| C_53
    C_5 -->|relates_to| C_14
    C_5 -->|relates_to| C_15
    C_5 -->|relates_to| C_23
    C_5 -->|relates_to| C_46
    C_60 -->|relates_to| C_19
    C_60 -->|relates_to| C_23
    C_60 -->|relates_to| C_35
    C_60 -->|relates_to| C_43
    C_60 -->|relates_to| C_48
    C_61 -->|relates_to| C_2
    C_61 -->|relates_to| C_27
    C_61 -->|relates_to| C_53
    C_62 -->|relates_to| C_29
    C_62 -->|relates_to| C_39
    C_62 -->|relates_to| C_32
    C_63 -->|relates_to| C_2
    C_63 -->|relates_to| C_22
    C_63 -->|relates_to| C_36
    C_63 -->|relates_to| C_43
    C_64 -->|relates_to| C_11
    C_64 -->|relates_to| C_24
    C_64 -->|relates_to| C_26
    C_64 -->|relates_to| C_25
    C_65 -->|relates_to| C_23
    C_65 -->|relates_to| C_43
    C_65 -->|relates_to| C_45
    C_65 -->|relates_to| C_42
    C_66 -->|relates_to| C_29
    C_66 -->|relates_to| C_39
    C_66 -->|relates_to| C_27
    C_66 -->|relates_to| C_53
    C_67 -->|relates_to| C_2
    C_67 -->|relates_to| C_14
    C_67 -->|relates_to| C_22
    C_67 -->|relates_to| C_27
    C_67 -->|relates_to| C_53
    C_68 -->|relates_to| C_27
    C_68 -->|relates_to| C_28
    C_68 -->|relates_to| C_36
    C_68 -->|relates_to| C_37
    C_68 -->|relates_to| C_51
    C_68 -->|relates_to| C_53
    C_6 -->|relates_to| C_2
    C_6 -->|relates_to| C_23
    C_6 -->|relates_to| C_27
    C_6 -->|relates_to| C_28
    C_6 -->|relates_to| C_35
    C_6 -->|relates_to| C_48
    C_6 -->|relates_to| C_49
    C_6 -->|relates_to| C_53
    C_7 -->|relates_to| C_22
    C_7 -->|relates_to| C_27
    C_7 -->|relates_to| C_13
    C_7 -->|relates_to| C_44
    C_8 -->|relates_to| C_20
    C_8 -->|relates_to| C_44
    C_8 -->|relates_to| C_51
    C_8 -->|relates_to| C_33
    C_9 -->|relates_to| C_29
    C_9 -->|relates_to| C_39
    C_9 -->|relates_to| C_32