name: Documentation Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  check-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Нужно для автокоммита
      pull-requests: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Нужна полная история для git
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Check documentation sync
      id: check
      continue-on-error: true
      run: |
        echo "🔍 Проверка синхронности документации..."
        python scripts/check_docs_sync.py --strict
        echo "exit_code=$?" >> $GITHUB_OUTPUT
        
    - name: Auto-update documentation if needed
      if: steps.check.outputs.exit_code == '2'
      run: |
        echo "⚙️ Автоматическое обновление документации..."
        python scripts/update_docs.py --auto
        
    - name: Commit and push if changed
      if: steps.check.outputs.exit_code == '2'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Проверяем, есть ли изменения
        if [[ -n $(git status --porcelain) ]]; then
          echo "📝 Обнаружены изменения в документации"
          git add CHANGELOG.md ASSESSMENT.md README.md
          git commit -m "docs: Auto-update documentation [skip ci]
          
          - Updated by GitHub Actions workflow
          - Triggered by commit ${{ github.sha }}
          - Auto-generated at $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          
          git push
          echo "✅ Документация обновлена и закоммичена"
        else
          echo "ℹ️ Нет изменений для коммита"
        fi
        
    - name: Final check
      if: steps.check.outputs.exit_code == '2'
      run: |
        echo "🔍 Финальная проверка после автообновления..."
        python scripts/check_docs_sync.py --strict
        
    - name: Comment on PR if auto-fixed
      if: steps.check.outputs.exit_code == '2' && github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ **Документация автоматически обновлена!**\n\n' +
                  'GitHub Actions обнаружил устаревшую документацию и автоматически обновил её.\n\n' +
                  'Изменённые файлы:\n' +
                  '- `CHANGELOG.md`\n' +
                  '- `ASSESSMENT.md`\n\n' +
                  'Подробности см. в [логах CI](' + context.payload.repository.html_url + '/actions/runs/' + context.runId + ').'
          })